### ISSUE TITLE
room parameter: encoding unclear

### ISSUE THREAD

**Issue by Adorfer** [fl0rp/bauchbinde#3]
how to encode room names with non-ascii-characters? 
tried different encodings and failed on 3 variants.

**Comment by fl0rp** [comment]
regular url encoding is all you should need to do, for example: 
https://franconian.net/bauchbinde/?room=hacc%20M%C3%BCnchen%20/%20about:future&time=2020-12-27T13:00:00+01:00

**Comment by Adorfer** [comment]
works now thanks
